name: Protos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: buf setup
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.15.1"

      - name: lint check
        run: buf lint proto

      - name: backward compatibility check
        continue-on-error: true
        run: buf breaking proto --against https://github.com/${GITHUB_REPOSITORY}.git#subdir=proto,branch=main

      - name: generate proto
        run: buf generate proto

      - name: commit generated proto
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "commit generated protos"

      - name: push generated proto
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
