name: Protos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: buf setup
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.15.1"
        run: buf --version
