name: Protos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: buf setup
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.15.1"

      - name: lint check
        run: buf lint proto

      - name: backward compatibility check
        continue-on-error: true
        run: buf breaking proto --against https://github.com/${GITHUB_REPOSITORY}.git#subdir=proto,branch=main
